"""WO-039-B — MP3 derivative via ffmpeg (WAV -> MP3) + async worker.

The MP3 is a *convenience* copy (W-039-B §16/§23).  It is NOT the forensic
source and is never treated as authoritative.  It is generated only AFTER the
WAV master has been safely finalized; an MP3 failure never invalidates the WAV.

:func:`encode_mp3` invokes the installed ffmpeg with a fixed argv list:

    ffmpeg -hide_banner -loglevel error -i <wav> -codec:a libmp3lame
           -b:a <bitrate> -ac <channels> -ar <sample_rate> -y <mp3>

It never uses ``shell=True`` and never accepts a user-controlled command string
(W-039-B §25/§39).  Paths are generated by the recorder inside the configured
archive root and are guarded against leading ``-`` (ffmpeg option injection).

:class:`Mp3Worker` runs MP3 encoding on a bounded background queue so encoding
can never block RTP reception or VAD (W-039-B §26/§31).  When the queue is full
a job is dropped (the WAV remains authoritative); the drop is recorded and
observable.

Author: Tactical Core Engineering Team
Version: 1.0
"""

from __future__ import annotations

import logging
import os
import queue
import subprocess
import threading
from dataclasses import dataclass

logger = logging.getLogger(__name__)


class Mp3EncodeError(Exception):
    """Raised when MP3 generation fails."""


def _safe_ffmpeg_path(path: str) -> str:
    """Reject ffmpeg argument injection from a generated filesystem path."""
    if path.startswith("-"):
        raise Mp3EncodeError(f"unsafe ffmpeg input path: {path!r}")
    return path


def encode_mp3(
    wav_path: str,
    mp3_path: str,
    *,
    bitrate: str = "64k",
    sample_rate: int = 8000,
    channels: int = 1,
    ffmpeg_path: str = "ffmpeg",
    timeout: float = 60.0,
) -> None:
    """Encode ``wav_path`` to ``mp3_path`` with ffmpeg (fixed argv, no shell).

    Args:
        wav_path: The finalized master WAV path.
        mp3_path: Destination MP3 path.
        bitrate: MP3 bitrate (e.g. ``"64k"``).
        sample_rate: Output sample rate (Hz).
        channels: Output channel count.
        ffmpeg_path: Path to the ffmpeg binary.
        timeout: Subprocess timeout (seconds).

    Raises:
        Mp3EncodeError: On ffmpeg failure, timeout, or missing output.
    """
    wav = _safe_ffmpeg_path(os.path.abspath(wav_path))
    mp3 = _safe_ffmpeg_path(os.path.abspath(mp3_path))
    directory = os.path.dirname(mp3)
    if directory:
        os.makedirs(directory, exist_ok=True)
    cmd = [
        ffmpeg_path,
        "-hide_banner",
        "-loglevel",
        "error",
        "-i",
        wav,
        "-codec:a",
        "libmp3lame",
        "-b:a",
        str(bitrate),
        "-ac",
        str(channels),
        "-ar",
        str(sample_rate),
        "-y",
        mp3,
    ]
    try:
        proc = subprocess.run(cmd, capture_output=True, timeout=timeout, check=False)
    except (subprocess.TimeoutExpired, OSError) as exc:
        raise Mp3EncodeError(f"MP3 encode failed (process error): {exc}") from exc
    if proc.returncode != 0:
        raise Mp3EncodeError(
            f"MP3 encode failed (rc={proc.returncode}): {proc.stderr[-400:].decode('utf-8', 'replace')}"
        )
    if not os.path.exists(mp3_path):
        raise Mp3EncodeError("MP3 output file was not created")


@dataclass(frozen=True)
class Mp3Job:
    """One queued WAV -> MP3 conversion."""

    wav_path: str
    mp3_path: str
    bitrate: str
    sample_rate: int
    channels: int


class Mp3Worker:
    """Bounded async queue that encodes MP3 derivatives on a background thread.

    Args:
        maxsize: Maximum queued jobs (backpressure bound).
        ffmpeg_path: Path to the ffmpeg binary.
        timeout: Per-encode subprocess timeout.
    """

    def __init__(
        self,
        maxsize: int = 100,
        ffmpeg_path: str = "ffmpeg",
        timeout: float = 60.0,
    ) -> None:
        self._queue: queue.Queue[Mp3Job] = queue.Queue(maxsize=maxsize)
        self._ffmpeg_path = ffmpeg_path
        self._timeout = timeout
        self._thread: threading.Thread | None = None
        self._stop = threading.Event()
        self._lock = threading.Lock()
        self._processed = 0
        self._failed = 0
        self._dropped = 0
        self._inflight = 0
        self._errors: list[str] = []

    # -- lifecycle ----------------------------------------------------------

    def start(self) -> None:
        with self._lock:
            if self._thread is not None:
                return
            self._stop.clear()
            self._thread = threading.Thread(
                target=self._run, name="wo039b-mp3-worker", daemon=True
            )
            self._thread.start()

    def stop(self, timeout: float = 2.0) -> None:
        self._stop.set()
        thread = self._thread
        if thread is not None and thread is not threading.current_thread():
            thread.join(timeout=timeout)
        self._thread = None

    # -- submission ---------------------------------------------------------

    def submit(self, job: Mp3Job) -> bool:
        """Queue a conversion.  Returns ``False`` when the queue is full.

        A dropped job means the MP3 is not generated; the WAV master is
        unaffected (W-039-B §31).
        """
        try:
            self._queue.put_nowait(job)
            return True
        except queue.Full:
            with self._lock:
                self._dropped += 1
            logger.warning("WO-039-B MP3 queue full; dropping MP3 for %s", job.wav_path)
            return False

    def wait_idle(self, timeout: float = 10.0) -> bool:
        """Block until the queue drains and no job is in flight.

        Returns ``True`` when idle, ``False`` on timeout.  Tracks both the
        queued count and in-flight jobs so it does not return while an encode is
        still running.
        """
        import time as _time

        end = _time.monotonic() + timeout
        while _time.monotonic() < end:
            with self._lock:
                if self._queue.qsize() == 0 and self._inflight == 0:
                    return True
            _time.sleep(0.02)
        with self._lock:
            return self._queue.qsize() == 0 and self._inflight == 0

    # -- observability ------------------------------------------------------

    def snapshot(self) -> dict:
        with self._lock:
            return {
                "queued": self._queue.qsize(),
                "inflight": self._inflight,
                "processed": self._processed,
                "failed": self._failed,
                "dropped": self._dropped,
                "errors": list(self._errors[-5:]),
            }

    # -- worker loop --------------------------------------------------------

    def _run(self) -> None:
        while not self._stop.is_set():
            try:
                job = self._queue.get(timeout=0.2)
            except queue.Empty:
                continue
            with self._lock:
                self._inflight += 1
            try:
                encode_mp3(
                    job.wav_path,
                    job.mp3_path,
                    bitrate=job.bitrate,
                    sample_rate=job.sample_rate,
                    channels=job.channels,
                    ffmpeg_path=self._ffmpeg_path,
                    timeout=self._timeout,
                )
                with self._lock:
                    self._processed += 1
            except Exception as exc:  # noqa: BLE001 - isolate a failed encode
                with self._lock:
                    self._failed += 1
                    self._errors.append(f"{job.mp3_path}: {exc}")
                logger.warning("WO-039-B MP3 encode failed for %s: %s", job.mp3_path, exc)
            finally:
                with self._lock:
                    self._inflight -= 1
                self._queue.task_done()
