from __future__ import annotations
from abc import ABC, abstractmethod
from typing import List, Optional

class IIdentityManager(ABC):
    @abstractmethod
    def resolve_identity(self, source: str, external_id: str, entity_type: str) -> Optional[str]: ...
    @abstractmethod
    def register_external_id(self, entity_id: str, source: str, external_id: str, entity_type: str) -> None: ...
    @abstractmethod
    def register_alias(self, entity_id: str, alias: str) -> None: ...
    @abstractmethod
    def merge_identity(self, primary_entity_id: str, secondary_entity_id: str) -> None: ...
    @abstractmethod
    def lookup(self, search_term: str) -> List[str]: ...
