"""Observation Events.

Internal event definitions for Observation Engine coordination.
Events are fire-and-forget and do NOT modify observations.

Author: Tactical Core Engineering Team
Version: 1.0
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class ObservationEventType(str, Enum):
    """Internal events generated by the Observation Engine."""

    OBSERVATION_RECEIVED = "observation.received"
    OBSERVATION_VALIDATED = "observation.validated"
    OBSERVATION_REJECTED = "observation.rejected"
    OBSERVATION_STORED = "observation.stored"
    OBSERVATION_FORWARDED = "observation.forwarded"
    OBSERVATION_FAILED = "observation.failed"


class ObservationEvent(BaseModel):
    """Base event for observation lifecycle.

    All observation events follow this structure.
    Events are immutable and do NOT modify the observation.
    """

    model_config = {"frozen": True}

    event_id: UUID = Field(
        default_factory=UUID,
        description="Unique event identifier",
    )
    """Unique event ID (auto-generated)."""

    event_type: ObservationEventType = Field(
        ...,
        description="Type of event",
    )
    """Type of internal event."""

    observation_id: Optional[UUID] = Field(
        default=None,
        description="ID of related observation",
    )
    """Related observation ID (if applicable)."""

    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Event timestamp (UTC)",
    )
    """When the event occurred."""

    data: Dict[str, Any] = Field(
        default_factory=dict,
        description="Event-specific data",
    )
    """Additional event data."""

    error_message: Optional[str] = Field(
        default=None,
        description="Error message if event represents a failure",
    )
    """Error details if this is a failure event."""


class ObservationReceivedEvent(ObservationEvent):
    """Event fired when observation is first received."""

    model_config = {"frozen": True}

    event_type: ObservationEventType = Field(
        default=ObservationEventType.OBSERVATION_RECEIVED,
    )

    source: str = Field(..., description="Source that sent the observation")
    source_type: str = Field(..., description="Type of source")


class ObservationValidatedEvent(ObservationEvent):
    """Event fired when observation passes validation."""

    model_config = {"frozen": True}

    event_type: ObservationEventType = Field(
        default=ObservationEventType.OBSERVATION_VALIDATED,
    )

    validation_errors: List[str] = Field(
        default_factory=list,
        description="Any non-blocking warnings",
    )


class ObservationRejectedEvent(ObservationEvent):
    """Event fired when observation fails validation."""

    model_config = {"frozen": True}

    event_type: ObservationEventType = Field(
        default=ObservationEventType.OBSERVATION_REJECTED,
    )

    rejected_data: Dict[str, Any] = Field(
        default_factory=dict,
        description="Original rejected data",
    )

    validation_errors: List[str] = Field(
        ...,
        description="List of validation errors",
    )


class ObservationStoredEvent(ObservationEvent):
    """Event fired when observation is persisted to storage."""

    model_config = {"frozen": True}

    event_type: ObservationEventType = Field(
        default=ObservationEventType.OBSERVATION_STORED,
    )


class ObservationForwardedEvent(ObservationEvent):
    """Event fired when observation is forwarded to pipeline."""

    model_config = {"frozen": True}

    event_type: ObservationEventType = Field(
        default=ObservationEventType.OBSERVATION_FORWARDED,
    )

    pipeline_target: str = Field(
        ...,
        description="Where the observation was forwarded",
    )


class ObservationFailedEvent(ObservationEvent):
    """Event fired when processing fails unexpectedly."""

    model_config = {"frozen": True}

    event_type: ObservationEventType = Field(
        default=ObservationEventType.OBSERVATION_FAILED,
    )

    error_code: str = Field(..., description="Error code")
    error_details: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional error context",
    )


class ObservationEventBus:
    """Event bus for observation lifecycle events.

    This is a simple event bus that allows components to subscribe
    to observation lifecycle events. Events are fire-and-forget.

    Thread Safety:
    This class is thread-safe for concurrent access.
    """

    def __init__(self):
        """Initialize event bus."""
        self._subscribers: Dict[ObservationEventType, List[callable]] = {
            event_type: [] for event_type in ObservationEventType
        }
        self._lock = __import__('threading').Lock()

    def subscribe(
        self,
        event_type: ObservationEventType,
        handler: callable
    ) -> str:
        """Subscribe to an event type.

        Args:
            event_type: Type of event to subscribe to.
            handler: Callable that handles the event.

        Returns:
            Subscription ID for unsubscribe.
        """
        import uuid
        subscription_id = str(uuid.uuid4())

        with self._lock:
            self._subscribers[event_type].append({
                "id": subscription_id,
                "handler": handler,
            })

        return subscription_id

    def unsubscribe(self, subscription_id: str) -> bool:
        """Unsubscribe from events.

        Args:
            subscription_id: Subscription ID to remove.

        Returns:
            True if unsubscribed, False if not found.
        """
        with self._lock:
            for subscribers in self._subscribers.values():
                for i, sub in enumerate(subscribers):
                    if sub["id"] == subscription_id:
                        subscribers.pop(i)
                        return True
        return False

    def publish(self, event: ObservationEvent) -> None:
        """Publish an event to all subscribers.

        Args:
            event: Event to publish.
        """
        with self._lock:
            subscribers = list(self._subscribers.get(event.event_type, []))

        # Notify subscribers outside lock
        for sub in subscribers:
            try:
                sub["handler"](event)
            except Exception:
                # Log but don't propagate
                pass

    def subscribe_all(self, handler: callable) -> str:
        """Subscribe to all observation events.

        Args:
            handler: Callable that handles all events.

        Returns:
            Subscription ID.
        """
        import uuid
        subscription_id = str(uuid.uuid4())

        with self._lock:
            for event_type in ObservationEventType:
                self._subscribers[event_type].append({
                    "id": subscription_id,
                    "handler": handler,
                    "subscribe_all": True,
                })

        return subscription_id

    def get_subscription_count(self, event_type: ObservationEventType) -> int:
        """Get number of subscribers for event type.

        Args:
            event_type: Event type to check.

        Returns:
            Number of active subscribers.
        """
        with self._lock:
            return len(self._subscribers.get(event_type, []))


# Global event bus instance (thread-safe singleton)
_observation_event_bus: Optional[ObservationEventBus] = None


def get_observation_event_bus() -> ObservationEventBus:
    """Get the global observation event bus.

    Returns:
        Global ObservationEventBus instance.
    """
    global _observation_event_bus
    if _observation_event_bus is None:
        _observation_event_bus = ObservationEventBus()
    return _observation_event_bus
