"""Observation Types.

Type definitions for the Observation Engine.
These types are derived from ENTITY-001 Constitutional Architecture.

Author: Tactical Core Engineering Team
Version: 1.0
"""

from enum import Enum


class ObservationType(str, Enum):
    """Classification of observation types.

    Based on the constitutional model, observations are created
    from various source systems. Each type represents a category
    of raw intelligence capture.
    """

    RADIO = "radio"
    """Radio transmission captured from multicast stream."""

    SIGNAL = "signal"
    """Signal message received from Signal Messenger."""

    ATAK = "atak"
    """ATAK map object updated via plugin."""

    REST_API = "rest_api"
    """Data received from external REST API."""

    OPERATOR = "operator"
    """Operator observation input."""

    SPEECH = "speech"
    """Speech transcription from audio processing."""

    CAMERA = "camera"
    """Camera alert or frame analysis."""

    SENSOR = "sensor"
    """Sensor data from IoT/field devices."""

    OTHER = "other"
    """Future plugin or unspecified source."""


class SourceType(str, Enum):
    """Classification of source system types.

    Indicates the category of system that created the observation.
    """

    DRIVER = "driver"
    """Observation created by a Driver component."""

    PLUGIN = "plugin"
    """Observation created by a Plugin."""

    API = "api"
    """Observation received via REST/WebSocket API."""

    OPERATOR = "operator"
    """Observation manually entered by operator."""

    AI = "ai"
    """Observation derived from AI analysis (e.g., callsign detection)."""

    SYSTEM = "system"
    """System-generated observation (e.g., heartbeat)."""


class ProcessingStatus(str, Enum):
    """Current processing status of an observation.

    Tracks the lifecycle state of the observation from
    ingestion to forwarding.
    """

    RECEIVED = "received"
    """Observation has been received and is pending validation."""

    VALIDATED = "validated"
    """Observation passed all validation checks."""

    REJECTED = "rejected"
    """Observation failed validation and was rejected."""

    STORED = "stored"
    """Observation has been persisted to storage."""

    FORWARDED = "forwarded"
    """Observation has been forwarded to the pipeline."""

    PROCESSING = "processing"
    """Observation is currently being processed."""

    FAILED = "failed"
    """Processing failed for an unexpected reason."""


class ObservationEventType(str, Enum):
    """Internal events generated by the Observation Engine.

    These events are for internal engine coordination and
    do not modify the observation itself.
    """

    OBSERVATION_RECEIVED = "observation.received"
    """Fired when observation is first received."""

    OBSERVATION_VALIDATED = "observation.validated"
    """Fired when observation passes validation."""

    OBSERVATION_REJECTED = "observation.rejected"
    """Fired when observation fails validation."""

    OBSERVATION_STORED = "observation.stored"
    """Fired when observation is persisted."""

    OBSERVATION_FORWARDED = "observation.forwarded"
    """Fired when observation is forwarded to pipeline."""

    OBSERVATION_FAILED = "observation.failed"
    """Fired when processing fails unexpectedly."""


class ConfidenceLevel(str, Enum):
    """Confidence level categories for observations.

    Represents the source-supplied confidence in the observation.
    Higher values indicate greater certainty.
    """

    LOW = "low"
    """Low confidence - significant uncertainty."""

    MEDIUM = "medium"
    """Medium confidence - some uncertainty."""

    HIGH = "high"
    """High confidence - strong certainty."""

    CERTAIN = "certain"
    """Certain - verified against multiple sources."""
