#!/usr/bin/env python3
"""
Evidence Generator for Tactical Core.

This script executes verification commands and records their output unchanged.
Never fabricates output or masks failures.
"""

import subprocess
import sys
import os
from datetime import datetime, timezone
from pathlib import Path


def get_timestamp():
    return datetime.now(timezone.utc).isoformat()


def execute_command(command, working_dir=None, description=""):
    """
    Execute a command and capture all output.

    Args:
        command: Command string to execute.
        working_dir: Working directory for execution.
        description: Human-readable description.

    Returns:
        Dictionary with command, stdout, stderr, exit_code.
    """
    result = {
        "command": command,
        "description": description,
        "working_directory": working_dir or os.getcwd(),
        "timestamp": get_timestamp(),
        "stdout": "",
        "stderr": "",
        "exit_code": -1,
    }
    try:
        # Execute subprocess.run() - actually executed, not simulated
        process = subprocess.run(
            command,
            shell=True,
            capture_output=True,
            text=True,
            cwd=working_dir,
            timeout=300,
        )
        # Capture stdout unchanged
        result["stdout"] = process.stdout
        # Capture stderr unchanged
        result["stderr"] = process.stderr
        # Capture exit code
        result["exit_code"] = process.returncode
    except Exception as e:
        # Record actual exception, do not mask
        result["stderr"] = str(e)
        result["exit_code"] = -3
    return result


def write_log(filepath, data):
    """Write log file with unchanged command output."""
    sep = "=" * 70
    lines = [
        sep,
        "COMMAND: " + data["command"],
        "WORKING DIRECTORY: " + data["working_directory"],
        "TIMESTAMP: " + data["timestamp"],
        sep,
        "",
        "STDOUT:",
        "-" * 70,
        data["stdout"] or "(empty)",
        "",
        "STDERR:",
        "-" * 70,
        data["stderr"] or "(empty)",
        "",
        "EXIT CODE: " + str(data["exit_code"]),
        sep,
    ]
    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text("\n".join(lines))
    print("Log written: " + str(filepath))


def write_evidence(filepath, results):
    """Write evidence document with unchanged output."""
    lines = [
        "# VERIFICATION EVIDENCE",
        "# Generated: " + get_timestamp(),
        "# DO NOT EDIT THIS FILE MANUALLY",
        ""
    ]
    for i, result in enumerate(results, 1):
        lines.extend([
            "",
            "=" * 70,
            "TEST " + str(i) + ": " + result.get("description", "N/A"),
            "=" * 70,
            "",
            "Command: " + result["command"],
            "Working Directory: " + result["working_directory"],
            "Timestamp: " + result["timestamp"],
            "",
            "STDOUT:",
            result["stdout"] or "(empty)",
            "",
            "STDERR:",
            result["stderr"] or "(empty)",
            "",
            "EXIT CODE: " + str(result["exit_code"]),
        ])
    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text("\n".join(lines))
    print("Evidence written: " + str(filepath))


def main():
    print("=" * 70)
    print("TACTICAL CORE - Evidence Generator")
    print("=" * 70)
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent
    backend_dir = repo_root / "backend"
    logs_dir = repo_root / "artifacts" / "logs"
    evidence_dir = repo_root / "docs"
    logs_dir.mkdir(parents=True, exist_ok=True)
    results = []
    overall_exit_code = 0

    print("\n[1/3] Testing Core Import...")
    result = execute_command(
        'python -c "import app.core"',
        working_dir=str(backend_dir),
        description="Core Import Verification",
    )
    write_log(logs_dir / "import_core.log", result)
    results.append(result)
    if result["exit_code"] != 0:
        overall_exit_code = 1

    print("\n[2/3] Collecting Tests...")
    result = execute_command(
        "pytest --collect-only",
        working_dir=str(backend_dir),
        description="Test Collection",
    )
    write_log(logs_dir / "pytest_collect.log", result)
    results.append(result)
    if result["exit_code"] != 0:
        overall_exit_code = 1

    print("\n[3/3] Running E2E Tests...")
    result = execute_command(
        "pytest backend/tests/test_signal_reference_plugin_e2e.py -v",
        working_dir=str(repo_root),
        description="Integration Tests",
    )
    write_log(logs_dir / "e2e.log", result)
    results.append(result)
    if result["exit_code"] != 0:
        overall_exit_code = 1

    print("\n" + "=" * 70)
    print("Generating Evidence Document...")
    evidence_file = evidence_dir / "SPRINT_5_0_EVIDENCE.md"
    write_evidence(evidence_file, results)

    print("\n" + "=" * 70)
    print("SUMMARY")
    print("=" * 70)
    for i, result in enumerate(results, 1):
        # Report actual status based on exit code - NO MASKING
        if result["exit_code"] == 0:
            status = "PASSED"
        else:
            status = "FAILED"
        print("Test " + str(i) + ": " + status + " (exit code " + str(result["exit_code"]) + ")")
    print("\nOverall Exit Code: " + str(overall_exit_code))
    return overall_exit_code


if __name__ == "__main__":
    sys.exit(main())
